services:
  - type: web
    name: tele-ytdownload-bot
    env: python
    buildCommand: "apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt"
    startCommand: "python bot.py"
    plan: free
